### ISSUE TITLE
Incompatible with 2023.1

### ISSUE THREAD

**Issue by sanyarnd** [mwalter/MavenDependencyChecker#4]
Hi, JB released 2023.1 was recently released https://www.jetbrains.com/idea/whatsnew/

**Comment by mwalter** [comment]
Hi! [Version 1.6.4](https://github.com/mwalter/MavenDependencyChecker/releases/tag/v1.6.4) with support for IntelliJ 2023.1 was released on 28th March.

**Comment by sanyarnd** [comment]
Thanks, strange that plugin managament didn't show new version
