### ISSUE TITLE
Dependency check error

### ISSUE THREAD

**Issue by pangho** [mwalter/MavenDependencyChecker#7]
1.10.2 version always prompt 
" No Project Dependencies
   No project dependency information found. Nothing to check."

but 1.9.0 is OK!

**Comment by mwalter** [comment]
Hi @pangho! I need more information about your issue. Please attach your POM file. Did you invalidate the caches of IntelliJ IDEA? Sometimes this may help.

**Comment by mwalter** [comment]
Due to no further information given I'll close this one.
